import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import vm from 'node:vm';
import {emptyAdvisor,checkAdvisor} from '../worker/advisor-model.js';
function fixture(){
 const decode=s=>s.replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>').replaceAll('&quot;','"');
 class Node{
  constructor(tag){this.tagName=tag.toUpperCase();this.children=[];this.attrs={};this.events={};this.dataset={};this.style={setProperty(){}};this.hidden=false;this._text='';this._value=undefined;this.className='';this.disabled=false;this.parentElement=null;this.classList={add:cls=>{this.className+=' '+cls;},remove:()=>{}};}
  get id(){return this.attrs.id;}set id(v){this.attrs.id=v;}get textContent(){return this._text+this.children.map(n=>n.textContent).join('');}set textContent(v){this._text=String(v);this.children=[];}
  get value(){if(this._value!==undefined)return this._value;if(this.tagName==='SELECT')return this.children.find(c=>c.attrs.selected!==undefined)?.value||this.children[0]?.value||'';if(this.tagName==='OPTION')return this.attrs.value??this.textContent;return this.attrs.value??(this.tagName==='TEXTAREA'?this.textContent:'');}set value(v){this._value=String(v);}
  set type(v){this.attrs.type=v;}get type(){return this.attrs.type;}set checked(v){this._checked=v;}get checked(){return this._checked||false;}get lastElementChild(){return this.children.at(-1);}
  append(...nodes){for(const n of nodes){if(n.parentElement)n.remove();n.parentElement=this;this.children.push(n);}}prepend(...nodes){for(const n of nodes.reverse()){n.remove();n.parentElement=this;this.children.unshift(n);}}replaceChildren(...nodes){this._text='';for(const n of this.children)n.parentElement=null;this.children=[];this.append(...nodes);}
  remove(){if(this.parentElement){const p=this.parentElement;p.children=p.children.filter(n=>n!==this);this.parentElement=null;}}insertBefore(n,b){n.remove();n.parentElement=this;this.children.splice(this.children.indexOf(b),0,n);}
  setAttribute(k,v){this.attrs[k]=String(v);if(k==='class')this.className=String(v);if(k==='hidden')this.hidden=true;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=String(v);}getAttribute(k){return this.attrs[k];}
  addEventListener(k,fn){(this.events[k]??=[]).push(fn);}async fire(k){for(const fn of this.events[k]||[])await fn({preventDefault(){},target:this,submitter:null});}click(){return this.fire('click');}focus(){document.activeElement=this;}scrollIntoView(){}
  contains(n){return this===n||this.children.some(c=>c.contains(n));}querySelector(s){return this.querySelectorAll(s)[0]||null;}querySelectorAll(s){const direct=s.includes('>');const parts=s.split(/\s*>\s*|\s+/).filter(Boolean);const matches=(n,part)=>{const attr=part.match(/\[([^=\]]+)(?:="?([^"\]]+)"?)?\]/);const tag=part.match(/^([a-z]+)/i)?.[1];const cls=part.match(/\.([\w-]+)/)?.[1];return (!tag||n.tagName===tag.toUpperCase())&&(!cls||n.className.split(/\s+/).includes(cls))&&(!attr||attr[1].startsWith('data-')?( !tag||n.tagName===tag.toUpperCase())&&(!cls||n.className.split(/\s+/).includes(cls))&&(!attr||n.dataset[attr[1].slice(5)]!==undefined&&(attr[2]===undefined||n.dataset[attr[1].slice(5)]===attr[2])):n.attrs[attr[1]]!==undefined);};
   const all=[];const scan=n=>{for(const c of n.children){all.push(c);scan(c);}};scan(this);return all.filter(n=>{if(!matches(n,parts.at(-1)))return false;let parent=n.parentElement;for(let i=parts.length-2;i>=0;i--){if(direct){if(!parent||!matches(parent,parts[i]))return false;parent=parent.parentElement;}else{while(parent&&!matches(parent,parts[i]))parent=parent.parentElement;if(!parent)return false;parent=parent.parentElement;}}return true;});}
  reset(){for(const n of this.querySelectorAll('input').concat(this.querySelectorAll('textarea'),this.querySelectorAll('select')))n._value=undefined;}
 }
 const document={activeElement:null,visibilityState:'visible',createElement:tag=>new Node(tag),createElementNS:(_,tag)=>new Node(tag)};
 const root=new Node('html'),stack=[root];const html=readFileSync('page.html','utf8');const markup=html.replace(/<script>[\s\S]*?<\/script>/g,'').replace(/<style>[\s\S]*?<\/style>/g,'');
 for(const token of markup.match(/<[^>]+>|[^<]+/g)||[]){if(token.startsWith('</')){const tag=token.slice(2,-1).trim().toUpperCase();while(stack.length>1&&stack.at(-1).tagName!==tag)stack.pop();if(stack.length>1)stack.pop();}else if(token.startsWith('<!'))continue;else if(token.startsWith('<')){const tag=token.match(/^<([\w-]+)/)?.[1];if(!tag)continue;const n=new Node(tag);for(const m of token.slice(tag.length+1,-1).matchAll(/([\w-]+)(?:="([^"]*)")?/g))n.setAttribute(m[1],decode(m[2]||''));stack.at(-1).append(n);if(!['meta','link','img','input','br','hr'].includes(tag))stack.push(n);}else stack.at(-1)._text+=decode(token.trim());}
 document.body=root.querySelector('body');document.querySelectorAll=s=>root.querySelectorAll(s);document.querySelector=s=>root.querySelector(s);document.getElementById=id=>{const find=n=>n.id===id?n:n.children.map(find).find(Boolean);return find(root);};
 let lastBlob;const saved=[];let docs={};const family={reports:[],discoveries:[],questions:[]};
 const context={console,Date,Intl,JSON,Error,Array,Number,Set,Map,Promise,Math,Uint8Array,TextEncoder,Blob,crypto,document,navigator:{onLine:true},window:{LDS_SITES:true,addEventListener(){},scrollTo(){},matchMedia(){return {matches:true}},speechSynthesis:{cancel(){},getVoices(){return[]},speak(){}}},speechSynthesis:{cancel(){},getVoices(){return[]},speak(){}},SpeechSynthesisUtterance:class{},Audio:class{play(){return Promise.resolve()}pause(){}},localStorage:{getItem(){return null},setItem(){},removeItem(){}},confirm:()=>true,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},URL:{createObjectURL(blob){lastBlob=blob;return 'blob:test'},revokeObjectURL(){}},fetch:async(path,options={})=>{if(path==='/api/session')return new Response(JSON.stringify({role:options.headers['x-lds-role'],ready:true}));if(path==='/api/teacher'&&options.method==='PUT'){docs=JSON.parse(options.body);saved.push(docs);return new Response('{"saved":true}');}if(path==='/api/teacher')return new Response(JSON.stringify({documents:docs,runs:[],...family}));return new Response(JSON.stringify(family));}};
 vm.createContext(context);vm.runInContext(html.split('<script>')[1].split('</script>')[0],context);
 return {run:code=>vm.runInContext(code,context),get:id=>document.getElementById(id),saved,blob:()=>lastBlob,async login(){document.getElementById('profile-select').value='israel';await document.getElementById('profile-select').fire('change');document.getElementById('access-code').value='TEST';await document.getElementById('access-form').fire('submit');assert.equal(document.getElementById('workspace').hidden,false);assert.equal(document.getElementById('status').textContent,'');}};
}
test('la página completa arranca y abre el panel del asesor con datos pendientes',async()=>{const f=fixture();await f.login();assert.equal(f.get('asesor').hidden,false);assert.ok(f.get('asesor').textContent.includes('Hola, Israel'));assert.ok(f.get('asesor').textContent.includes('0Encuentros registrados'));assert.equal(f.run('advisor.goals.length'),0);});
test('planeación, apertura y registro conservan los apoyos y cierran el encuentro',async()=>{const f=fixture();await f.login();f.run("fillAdvisorPlan('Valoración 1')");f.get('advisor-plan-date').value='2026-10-08T16:00';await f.get('advisor-plan-form').fire('submit');assert.equal(f.run('advisor.plans.length'),1);assert.equal(f.run('advisor.plans[0].blocks.reduce((n,b)=>n+b.minutes,0)'),45);f.run('startAdvisorPlan(advisor.plans[0].id)');f.get('advisor-session-achievement').value='Separó sonidos con fichas.';f.get('advisor-session-support').value='Modelo y fichas.';f.get('advisor-session-fatigue').value='Pidió pausa';f.run('captureAdvisorSessionDraft()');await f.run('flushTeacherSave()');assert.equal(f.saved.at(-1).advisor.sessionDraft.achievement,'Separó sonidos con fichas.');await f.get('session-form').fire('submit');await f.run('flushTeacherSave()');assert.equal(f.saved.at(-1).state.sessions[0].detail.fatigue,'Pidió pausa');assert.equal(f.saved.at(-1).advisor.plans[0].status,'Realizada');assert.deepEqual(f.saved.at(-1).advisor.sessionDraft,{});});
test('una meta conserva sus muestras al editarse y prepara una devolución revisable',async()=>{const f=fixture();await f.login();f.get('advisor-goal-objective').value='Leer palabras nuevas.';f.get('advisor-goal-criterion').value='8 de 10 sin ayuda en dos encuentros.';await f.get('advisor-goal-form').fire('submit');const id=f.run('advisor.goals[0].id');const base='advisor-sample-'+id;f.get(base+'-correct').value='6';f.get(base+'-total').value='10';f.get(base+'-material').value='Sílabas directas';await f.get(base+'-date').parentElement.fire('submit');assert.equal(f.run('advisor.goals[0].samples[0].correct'),6);f.run('editAdvisorGoal(advisor.goals[0].id)');f.get('advisor-goal-objective').value='Leer diez palabras nuevas.';await f.get('advisor-goal-form').fire('submit');assert.equal(f.run('advisor.goals[0].samples.length'),1);f.run('prepareAdvisorReview()');assert.ok(f.run('assessment.nextGoals').includes('8 de 10'));assert.equal(f.get('publicar').hidden,false);assert.equal(f.run('familySnapshot.reports.length'),0);});
test('el PDF del asesor tiene varias páginas y conserva los acentos',async()=>{const f=fixture();await f.login();f.run("downloadAdvisorPDF('Valoración pedagógica',[['Evidencia','Comprensión y precisión.\\n'.repeat(120)]],'prueba')");const bytes=Buffer.from(await f.blob().arrayBuffer());assert.ok(bytes.toString('latin1').includes('Comprensión'));assert.ok(bytes.toString('latin1').includes('/Count 4'));writeFileSync('/tmp/advisor-report-example.pdf',bytes);});
test('corregir una muestra reemplaza el dato y cerrar sesión limpia las notas del panel',async()=>{const f=fixture();await f.login();f.get('advisor-goal-objective').value='Leer palabras.';f.get('advisor-goal-criterion').value='8 de 10 con patrones enseñados.';await f.get('advisor-goal-form').fire('submit');const base='advisor-sample-'+f.run('advisor.goals[0].id');f.get(base+'-correct').value='5';f.get(base+'-total').value='10';f.get(base+'-material').value='Palabras de muestra';await f.get(base+'-form').fire('submit');f.run('editAdvisorSample(advisor.goals[0].id,advisor.goals[0].samples[0].id)');f.get(base+'-correct').value='6';await f.get(base+'-form').fire('submit');assert.equal(f.run('advisor.goals[0].samples.length'),1);assert.equal(f.run('advisor.goals[0].samples[0].correct'),6);await f.get('logout').fire('click');assert.equal(f.get('workspace').hidden,true);assert.equal(f.get('asesor').children.length,0);assert.equal(f.get('metas-asesor').children.length,0);assert.equal(f.run('advisor.goals.length'),0);});
