let advisor=emptyAdvisor();
const advisorSessionFields=['date','week','focus','objective','material','correct','total','oral','reading','evidence','next'];
const advisorDetailFields=['confidence','participation','fatigue','support','errors','achievement','home'];
const advisorLabels={interests:'Intereses y formas de motivarlo',school:'Lo que está trabajando en segundo grado',history:'Antecedentes de lectura, escritura y apoyos recibidos',supports:'Apoyos que le ayudan y situaciones que le cuestan',agreements:'Acuerdos con la familia y la escuela'};
function advisorCard(title,note){const card=elem('article',undefined,'card');if(title)card.append(elem('h2',title));if(note)card.append(elem('p',note,'advisor-section-note'));return card;}
function advisorButton(label,fn,primary=false){const b=action(label,fn);if(primary)b.classList.add('advisor-primary');return b;}
function advisorField(root,id,label,value='',options={}){
 const l=elem('label',label);l.htmlFor=id;let input;
 if(options.choices){input=elem('select');for(const choice of options.choices){const o=elem('option',Array.isArray(choice)?choice[1]:choice);o.value=Array.isArray(choice)?choice[0]:choice;input.append(o);}}
 else{input=elem(options.multiline?'textarea':'input');if(!options.multiline)input.type=options.type||'text';input.maxLength=options.max||1000;}
 input.id=id;input.value=value??'';if(options.required)input.required=true;if(options.min!==undefined)input.min=options.min;if(options.maxNumber!==undefined)input.max=options.maxNumber;if(options.type==='number')input.step='1';if(options.placeholder)input.placeholder=options.placeholder;
 if(options.onchange)input.addEventListener(options.choices?'change':'input',()=>options.onchange(input.value));root.append(l,input);return input;
}
function advisorSave(){scheduleTeacherSave();renderAdvisorHome();}
function advisorStatus(message){const p=$('advisor-save');if(p)p.textContent=message;}
function advisorGo(view){show(view);const section=$(view);const title=section?.querySelector('h2');if(title){title.tabIndex=-1;title.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'smooth'});}
function advisorHumanDate(value){if(!value)return 'Por acordar';const [date,time]=value.split('T');const [year,month,day]=date.split('-');return day+'/'+month+'/'+year+(time?' · '+time:'');}
function buildAdvisorWorkspace(){if(activeRole!=='israel')return;const nav=document.querySelector('main>nav');for(const view of ['asesor','perfil-asesor','diagnostico','plan-asesor','sesiones','metas-asesor','publicar','reportes','alumno','programa']){const button=document.querySelector('[data-view="'+view+'"]');if(nav&&button)nav.append(button);}buildAdvisorProfile();buildAdvisorPlanning();buildAdvisorGoals();buildAdvisorSessionFields();renderAdvisorHome();}
function renderAdvisorHome(){
 const root=$('asesor');if(!root||activeRole!=='israel')return;root.replaceChildren();
 const hero=elem('div',undefined,'advisor-hero');hero.append(elem('span','ESPACIO DEL ASESOR','advisor-eyebrow'),elem('h2','Hola, Israel.'),elem('p','Observa, enseña y ajusta. Cada encuentro deja una evidencia para decidir el siguiente paso.'),elem('span','2.º de primaria · 3 encuentros por semana · 45 minutos flexibles','advisor-pill'));
 const save=elem('p',cloudConnected?'Guardado compartido activo.':'Conectando el seguimiento…','advisor-save');save.id='advisor-save';save.setAttribute('role','status');hero.append(save);root.append(hero);
 const observed=Object.values(assessment.observations).filter(o=>!['pendiente','no_aplicado'].includes(o.level)).length;
 const stats=elem('div',undefined,'advisor-stats');for(const [value,label] of [[state.sessions.length,'Encuentros registrados'],[observed,'Ítems valorados'],[advisor.goals.filter(g=>g.status==='En trabajo').length,'Metas en trabajo'],[(familySnapshot.questions||[]).filter(q=>!q.answer).length,'Mensajes por responder']]){const c=elem('div',undefined,'advisor-stat');c.append(elem('strong',String(value)),elem('span',label));stats.append(c);}root.append(stats);
 const shortcuts=elem('div',undefined,'advisor-shortcuts');for(const [view,title,note] of [['plan-asesor','Preparar encuentro','Objetivo, tiempos y materiales.'],['diagnostico','Valorar el punto de partida','Tres encuentros para conocerlo.'],['sesiones','Registrar lo observado','Resultados, apoyos y siguiente paso.'],['publicar','Preparar devolución','Revisar y publicar para la familia.']]){const b=advisorButton('',()=>advisorGo(view));b.className='advisor-shortcut';b.append(elem('strong',title),elem('span',note));shortcuts.append(b);}root.append(shortcuts);
 const grid=elem('div',undefined,'advisor-grid');const next=advisorCard('Tu próximo encuentro');const pending=advisor.plans.filter(p=>p.status!=='Realizada').sort((a,b)=>a.date.localeCompare(b.date));const plan=pending.find(p=>p.date.slice(0,10)>=advisorDateToday())||pending[0];
 if(plan){next.append(elem('span',advisorHumanDate(plan.date),'advisor-pill'),elem('h3',plan.objective),elem('p',plan.materials||'Anota los materiales antes del encuentro.'),advisorButton('Abrir la sesión',()=>startAdvisorPlan(plan.id),true));}else next.append(elem('p','Todavía no hay un encuentro programado. Prepara la primera valoración y acuerda su fecha.','advisor-empty'),advisorButton('Planear el primer encuentro',()=>{advisorGo('plan-asesor');fillAdvisorPlan('Valoración 1');},true));grid.append(next);
 const route=advisorCard('Qué sigue');const checks=[['perfil-asesor',Object.values(advisor.checks).filter(Boolean).length+'/4','Entrevista y acuerdos'],['diagnostico',observed?'En proceso':'Pendiente','Valoración pedagógica'],['metas-asesor',advisor.goals.length?advisor.goals.length+' metas':'Pendiente','Plan individual'],['publicar',familySnapshot.reports?.length?'Publicado':'Por preparar','Devolución a la familia']];for(const [view,badge,label] of checks){const row=elem('div',undefined,'advisor-item');row.append(elem('span',badge,'advisor-pill'),advisorButton(label,()=>advisorGo(view)));route.append(row);}grid.append(route);root.append(grid);
 const review=advisorCard('Próxima revisión del programa','Revisar evidencias en las semanas 4, 8 y 12; ajustar antes si el apoyo no está funcionando.');review.append(elem('p',advisor.reviewDate?advisorHumanDate(advisor.reviewDate):'Fecha de revisión por acordar.'),advisorButton('Revisar metas y avances',()=>advisorGo('metas-asesor')),elem('p','Compara materiales semejantes y el apoyo ofrecido. La precisión, la comprensión y el esfuerzo se observan por separado.','advisor-callout'));root.append(review);
 if(typeof teacherSaveRevision!=='undefined'&&teacherSaveRevision>teacherSavedRevision)advisorStatus('Hay cambios por guardar…');
}
function buildAdvisorProfile(){
 const root=$('perfil-asesor');root.replaceChildren();const card=advisorCard('Conocer al alumno','Usa la entrevista, sus trabajos escolares y tus observaciones para elegir el punto de partida.');
 for(const [key,label] of Object.entries(advisorLabels))advisorField(card,'advisor-context-'+key,label,advisor.context[key],{multiline:true,max:3000,onchange:value=>{advisor.context[key]=value;advisorSave();}});
 const dates=elem('div',undefined,'advisor-form-row');for(const [key,label] of [['startDate','Inicio del programa'],['reviewDate','Próxima revisión con la familia']]){const col=elem('div');advisorField(col,'advisor-'+key,label,advisor[key],{type:'date',onchange:value=>{advisor[key]=value;advisorSave();}});dates.append(col);}card.append(dates);root.append(card);
 const checks=advisorCard('Preparación y acuerdos','Marca cada punto cuando esté realizado.');const items=elem('div',undefined,'advisor-checks');for(const [key,label] of [['interview','Entrevista familiar realizada'],['schoolwork','Trabajos escolares y contenidos del grado revisados'],['report','Informe diagnóstico y recomendaciones revisados'],['coordination','Autorización familiar para coordinar con la escuela acordada']]){const l=elem('label');const c=elem('input');c.type='checkbox';c.checked=advisor.checks[key];c.addEventListener('change',()=>{advisor.checks[key]=c.checked;advisorSave();});l.append(c,elem('span',label));items.append(l);}checks.append(items);root.append(checks);
 root.append(advisorCard('Un punto de partida compartido','Revisa lo que ya se le enseñó, su lengua de escolarización y los apoyos disponibles. Con los acuerdos de la familia, coordina objetivos y adaptaciones con su docente.'));
}
function buildAdvisorPlanning(){
 const root=$('plan-asesor');root.replaceChildren();root.append(elem('h2','Planear cada encuentro'),elem('p','Tres días por semana, preferentemente alternos. Ajusta los bloques y ofrece pausas cuando las necesite.','advisor-section-note'));
 const form=elem('form',undefined,'card');form.id='advisor-plan-form';form.append(elem('h3','Preparar un encuentro'));
 const row=elem('div',undefined,'advisor-form-row');const a=elem('div'),b=elem('div');advisorField(a,'advisor-plan-date','Fecha y hora (Ciudad de México)','',{type:'datetime-local',required:true});advisorField(b,'advisor-plan-week','Semana',1,{type:'number',min:1,maxNumber:12,required:true});row.append(a,b);form.append(row);
 advisorField(form,'advisor-plan-kind','Tipo de encuentro','Intervención',{choices:['Valoración 1','Valoración 2','Valoración 3','Intervención'],onchange:fillAdvisorPlan});
 advisorField(form,'advisor-plan-objective','Objetivo concreto','',{required:true,max:1500,placeholder:'Qué esperas que pueda hacer y con qué apoyo.'});
 advisorField(form,'advisor-plan-patterns','Sonidos, letras o patrones que trabajarás','',{multiline:true,max:1500});advisorField(form,'advisor-plan-materials','Materiales y actividades','',{multiline:true,max:1500});
 form.append(elem('h3','Ruta del encuentro'));advisorBlocks.forEach(([title,minutes,description],i)=>{const block=elem('div',undefined,'advisor-plan-block');const titleRoot=elem('div');const titleNode=elem('strong',title);titleNode.id='advisor-block-title-'+i;titleRoot.append(titleNode);const time=elem('div');advisorField(time,'advisor-block-minutes-'+i,'Minutos',minutes,{type:'number',min:0,maxNumber:45,required:true,onchange:updateAdvisorPlanMinutes});block.append(titleRoot,time);advisorField(block,'advisor-block-description-'+i,'Qué harás',description,{multiline:true,max:1500});form.append(block);});
 const total=elem('p','','advisor-plan-total');total.id='advisor-plan-total';form.append(total);advisorField(form,'advisor-plan-home','Práctica breve para casa','',{multiline:true,max:1500,placeholder:'5–10 minutos. Solo habilidades ya enseñadas.'});
 const submit=elem('button','Guardar encuentro','advisor-primary');submit.type='submit';form.append(submit);form.addEventListener('submit',async e=>{e.preventDefault();if(submit.disabled)return;submit.disabled=true;try{const p={id:form.dataset.editId||crypto.randomUUID(),date:$('advisor-plan-date').value,week:Number($('advisor-plan-week').value),kind:$('advisor-plan-kind').value,status:advisor.plans.find(old=>old.id===form.dataset.editId)?.status||'Programada',objective:$('advisor-plan-objective').value,patterns:$('advisor-plan-patterns').value,materials:$('advisor-plan-materials').value,home:$('advisor-plan-home').value,blocks:advisorBlocks.map((_,i)=>({title:$('advisor-block-title-'+i).textContent,minutes:Number($('advisor-block-minutes-'+i).value),description:$('advisor-block-description-'+i).value}))};const next={...advisor,plans:form.dataset.editId?advisor.plans.map(old=>old.id===p.id?p:old):[...advisor.plans,p]};advisor=checkAdvisor(next);scheduleTeacherSave();await flushTeacherSave();buildAdvisorPlanning();renderAdvisorHome();notify('Encuentro guardado. Puedes abrirlo al iniciar la sesión.');}catch(error){notify(error.message);}finally{submit.disabled=false;}});root.append(form);
 const list=elem('div',undefined,'advisor-plan-list');list.id='advisor-plan-list';root.append(list);renderAdvisorPlans();updateAdvisorPlanMinutes();
}
function fillAdvisorPlan(kind){
 $('advisor-plan-kind').value=kind;const diagnostic=/Valoración ([123])/.exec(kind);const p=diagnostic?sessionsPlan[Number(diagnostic[1])-1]:null;
 if(p){$('advisor-plan-objective').value=p.goal;$('advisor-plan-materials').value=p.tasks.map(t=>t.title).join('\n');$('advisor-plan-patterns').value='Primer intento sin ayuda. Registrar el apoyo ofrecido después.';$('advisor-plan-home').value='Escuchar un cuento por placer. Evitar ensayar los ítems de la valoración.';const n=Number(diagnostic[1]);const routes={1:['Anticipa la actividad y pregunta cómo llega. Conversa sin exigir lectura.',p.tasks.slice(0,2).map(t=>t.title+': '+t.guide).join('\n'),p.tasks.slice(2,4).map(t=>t.title+': '+t.guide).join('\n'),p.tasks[4].guide,'Conversar sobre algo que le gusta. Observar vocabulario y relato sin puntuar sus gustos.','Reconocer su esfuerzo. Registrar atención, pausas y siguiente paso.'],2:['Anticipa lo que harán. Recordar que puede pedir una pausa.',p.tasks[0].guide,p.tasks[1].guide,'Ofrecer una pausa breve y revisar su disposición.',p.tasks[2].guide+'\n'+p.tasks[2].story,'Registrar las ayudas y reconocer algo que pudo hacer.'],3:['Anticipar lectura, conversación y escritura.',p.tasks[0].guide,p.tasks[1].guide,'Ofrecer una pausa breve y revisar su disposición.',p.tasks.slice(2).map(t=>t.title+': '+t.guide).join('\n'),'Reconocer su esfuerzo. Registrar los apoyos y acordar el siguiente paso.']};const materials={1:'Fichas, tarjetas de letras, lápiz, libro y hoja. Guías en Valoración inicial.',2:'Tarjetas de palabras y palabras inventadas. Cuento El jardín de Ana (en Valoración inicial).',3:'Texto El perro de Luis (en Valoración inicial), hoja y lápiz.'};$('advisor-plan-materials').value=materials[n];const descriptions=routes[n];advisorBlocks.forEach((_,i)=>$('advisor-block-description-'+i).value=descriptions[i]);}
 else{advisorBlocks.forEach(([title,minutes,description],i)=>{$('advisor-block-title-'+i).textContent=title;$('advisor-block-minutes-'+i).value=minutes;$('advisor-block-description-'+i).value=description;});}
 if(diagnostic){const routes={1:[['Bienvenida',5],['Entrevista y consignas',10],['Sonidos del habla',10],['Letras y sonidos',10],['Juego de lenguaje',5],['Cierre',5]],2:[['Bienvenida',5],['Lectura de palabras',12],['Palabras inventadas',5],['Pausa',3],['Cuento escuchado y relato',17],['Cierre',3]],3:[['Bienvenida',5],['Lectura de texto',10],['Conversación',10],['Pausa',3],['Escritura y mensaje',14],['Cierre',3]]};routes[Number(diagnostic[1])].forEach(([title,minutes],i)=>{$('advisor-block-title-'+i).textContent=title;$('advisor-block-minutes-'+i).value=minutes;});}
 updateAdvisorPlanMinutes();
}
function updateAdvisorPlanMinutes(){const total=$('advisor-plan-total');if(total)total.textContent=advisorBlocks.reduce((n,_,i)=>n+Number($('advisor-block-minutes-'+i).value||0),0)+' minutos orientativos · Integra las pausas dentro del encuentro.';}
function renderAdvisorPlans(){
 const root=$('advisor-plan-list');if(!root)return;root.replaceChildren();if(!advisor.plans.length){root.append(elem('p','Los encuentros aparecerán aquí cuando los prepares.','advisor-empty'));return;}
 for(const p of [...advisor.plans].sort((a,b)=>a.date.localeCompare(b.date))){const card=advisorCard('');card.append(elem('span',advisorHumanDate(p.date)+' · Semana '+p.week,'advisor-pill'),elem('h3',p.kind+' · '+p.objective),elem('p',p.patterns,'advisor-detail'));const details=elem('details');details.append(elem('summary','Ruta y materiales'));for(const block of p.blocks)details.append(elem('p',block.minutes+' min · '+block.title+'\n'+block.description,'advisor-detail'));details.append(elem('p','Materiales: '+(p.materials||'Por preparar'),'advisor-detail'),elem('p','En casa: '+(p.home||'Por acordar'),'advisor-detail'));card.append(details);
 const status=advisorField(card,'advisor-plan-status-'+p.id,'Estado',p.status,{choices:['Programada','Realizada','Reprogramar'],onchange:value=>{p.status=value;advisorSave();}});const actions=elem('div',undefined,'advisor-actions');actions.append(advisorButton('Abrir encuentro',()=>startAdvisorPlan(p.id),true),advisorButton('Editar plan',()=>editAdvisorPlan(p.id)),advisorButton('Ficha en PDF',()=>downloadAdvisorPlan(p)));card.append(actions);root.append(card);}
}
function editAdvisorPlan(id){const p=advisor.plans.find(p=>p.id===id);if(!p)return;const form=$('advisor-plan-form');form.dataset.editId=id;for(const key of ['date','week','kind','objective','patterns','materials','home'])$('advisor-plan-'+key).value=p[key];p.blocks.forEach((b,i)=>{$('advisor-block-title-'+i).textContent=b.title;$('advisor-block-minutes-'+i).value=b.minutes;$('advisor-block-description-'+i).value=b.description;});updateAdvisorPlanMinutes();form.scrollIntoView({behavior:'smooth',block:'start'});$('advisor-plan-objective').focus();}
function startAdvisorPlan(id){
 const p=advisor.plans.find(p=>p.id===id);if(!p)return;if(advisor.sessionDraft.objective&&advisor.activePlanId===id){advisorGo('sesiones');return;}if(advisor.sessionDraft.objective&&advisor.activePlanId!==id&&!confirm('Hay una sesión en preparación. ¿Reemplazar su borrador con este encuentro?'))return;
 advisor.activePlanId=id;advisor.sessionDraft={date:p.date.slice(0,10),week:String(p.week),focus:p.kind==='Intervención'?'Enseñar y practicar':'Valoración pedagógica e inicio',objective:p.objective.slice(0,300),material:[p.patterns,p.materials].filter(Boolean).join(' · ').slice(0,300),next:p.home.slice(0,1000),home:p.home};
 $('session-form').reset();restoreAdvisorSessionDraft();advisorSave();advisorGo('sesiones');
}
function buildAdvisorSessionFields(){
 if($('advisor-session-details')){$('advisor-session-details').remove();}const form=$('session-form');const group=elem('div');group.id='advisor-session-details';group.append(elem('h3','Cómo vivió el encuentro'));
 const row=elem('div',undefined,'advisor-form-row');for(const [key,label,choices] of [['confidence','Confianza',['No observada','Tranquilo','Necesitó confianza','Evitó la actividad']],['participation','Participación',['No observada','Participó','Con acompañamiento','Participación breve']],['fatigue','Cansancio',['No observada','Sin señales','Pidió pausa','Se detuvo']]]){const col=elem('div');advisorField(col,'advisor-session-'+key,label,'No observada',{choices});row.append(col);}group.append(row);
 for(const [key,label] of [['support','Apoyos que ayudaron'],['errors','Errores y autocorrecciones observados'],['achievement','Un logro concreto'],['home','Práctica breve para casa']])advisorField(group,'advisor-session-'+key,label,'',{multiline:true,max:1500});
 form.insertBefore(group,form.querySelector('.actions'));if(!form.dataset.advisorBound){form.addEventListener('input',captureAdvisorSessionDraft);form.addEventListener('change',captureAdvisorSessionDraft);form.dataset.advisorBound='true';}
 restoreAdvisorSessionDraft();
}
function captureAdvisorSessionDraft(){if(activeRole!=='israel')return;const draft={};for(const key of advisorSessionFields)draft[key]=$(key).value;for(const key of advisorDetailFields)draft[key]=$('advisor-session-'+key)?.value||'';advisor.sessionDraft=draft;advisorSave();}
function restoreAdvisorSessionDraft(){for(const key of advisorSessionFields)if(advisor.sessionDraft[key]!==undefined)$(key).value=advisor.sessionDraft[key];for(const key of advisorDetailFields)if(advisor.sessionDraft[key]!==undefined&&$('advisor-session-'+key))$('advisor-session-'+key).value=advisor.sessionDraft[key];}
function readAdvisorSessionDetail(){const d={planId:advisor.activePlanId};for(const key of advisorDetailFields)d[key]=$('advisor-session-'+key)?.value||'';return cleanSessionDetail(d);}
function afterAdvisorSession(session){
 const p=advisor.plans.find(p=>p.id===advisor.activePlanId);if(p)p.status='Realizada';advisor.activePlanId='';advisor.sessionDraft={};for(const key of advisorDetailFields)if($('advisor-session-'+key))$('advisor-session-'+key).value=['confidence','participation','fatigue'].includes(key)?'No observada':'';
 advisorSave();renderAdvisorPlans();
}
function buildAdvisorGoals(){
 const root=$('metas-asesor');root.replaceChildren();root.append(elem('h2','Metas y evidencias de avance'),elem('p','Define tres o cuatro prioridades después de la valoración. Escribe el criterio y registra intentos comparables.','advisor-section-note'));
 const form=elem('form',undefined,'card');form.id='advisor-goal-form';form.append(elem('h3','Definir una meta'));advisorField(form,'advisor-goal-area','Área',advisorAreas[0],{choices:advisorAreas});advisorField(form,'advisor-goal-objective','Qué aprenderá','',{required:true,placeholder:'Ejemplo: leer palabras nuevas con los patrones enseñados.'});advisorField(form,'advisor-goal-baseline','Punto de partida observado','',{multiline:true,placeholder:'Qué logró, con qué material y con qué ayuda.'});advisorField(form,'advisor-goal-criterion','Criterio para considerar el avance','',{required:true,multiline:true,placeholder:'Ejemplo orientativo: 8 de 10 palabras nuevas, sin ayuda, en dos encuentros. Ajusta a su punto de partida.'});advisorField(form,'advisor-goal-support','Apoyo permitido','',{placeholder:'Ejemplo: señalar las letras; sin decir la palabra.'});advisorField(form,'advisor-goal-material','Material para comparar intentos','',{placeholder:'Patrones y dificultad que conservarás en las muestras.'});advisorField(form,'advisor-goal-reviewDate','Fecha de revisión',advisor.reviewDate,{type:'date'});
 const submit=elem('button','Guardar meta','advisor-primary');submit.type='submit';form.append(submit);form.addEventListener('submit',async e=>{e.preventDefault();if(submit.disabled)return;submit.disabled=true;try{const g={id:form.dataset.editId||crypto.randomUUID(),status:'En trabajo',samples:[],area:$('advisor-goal-area').value};for(const key of ['objective','baseline','criterion','support','material','reviewDate'])g[key]=$('advisor-goal-'+key).value;const old=advisor.goals.find(old=>old.id===g.id);if(old){g.samples=old.samples;g.status=old.status;}advisor=checkAdvisor({...advisor,goals:old?advisor.goals.map(old=>old.id===g.id?g:old):[...advisor.goals,g]});scheduleTeacherSave();await flushTeacherSave();buildAdvisorGoals();renderAdvisorHome();notify('Meta guardada. Registra una evidencia cuando la observes.');}catch(error){notify(error.message);}finally{submit.disabled=false;}});root.append(form);
 const list=elem('div');list.id='advisor-goals-list';root.append(list);const comparison=advisorCard('Comprender al escuchar y al leer','Describe cada modalidad por separado. Los relatos de la valoración permiten una comparación cualitativa; no son pruebas equivalentes.');const choose=advisorField(comparison,'advisor-comparison-session','Encuentro que vas a revisar','',{choices:state.sessions.length?state.sessions.map((s,i)=>[String(i),advisorHumanDate(s.date)+' · '+s.objective.slice(0,60)]):[['','Sin registros todavía']],onchange:renderAdvisorComparison});if(state.sessions.length)choose.value=String(state.sessions.length-1);const pair=elem('div',undefined,'advisor-comparison');pair.id='advisor-comparison';comparison.append(pair);root.append(comparison);renderAdvisorProgress();renderAdvisorComparison();
 const review=advisorCard('Revisión del programa','Semanas 4, 8 y 12: qué cambió, qué apoyo necesita y cómo vas a ajustar la enseñanza.');for(const [key,label] of [['achievements','Avances sustentados en evidencias'],['pending','Necesidades que siguen presentes'],['adjustments','Ajustes a la enseñanza y a los apoyos'],['school','Acuerdos para las actividades escolares'],['decision','Decisión: continuar, ajustar o coordinar otros apoyos']])advisorField(review,'advisor-review-'+key,label,advisor.review[key],{multiline:true,max:3000,onchange:value=>{advisor.review[key]=value;advisorSave();}});
 const actions=elem('div',undefined,'advisor-actions');actions.append(advisorButton('Llevar metas y balance al reporte',prepareAdvisorReview,true),advisorButton('Descargar seguimiento en PDF',downloadAdvisorSummary));review.append(actions);root.append(review);
}
function renderAdvisorProgress(){
 const root=$('advisor-goals-list');if(!root||activeRole!=='israel')return;root.replaceChildren();if(!advisor.goals.length)root.append(elem('p','Las metas aparecerán después de que definas el punto de partida.','advisor-empty'));
 for(const g of advisor.goals){const card=elem('article',undefined,'advisor-goal');card.append(elem('span',g.area,'advisor-pill'),elem('h3',g.objective));const dl=elem('dl');for(const [label,value] of [['Punto de partida',g.baseline||'Por completar'],['Criterio',g.criterion],['Apoyo permitido',g.support||'Por precisar'],['Material',g.material||'Por precisar'],['Revisión',advisorHumanDate(g.reviewDate)]])dl.append(elem('dt',label),elem('dd',value));card.append(dl);
 advisorField(card,'advisor-goal-status-'+g.id,'Decisión del asesor',g.status,{choices:['En trabajo','Consolidada','Reformular'],onchange:value=>{g.status=value;advisorSave();}});
 if(g.samples.length){const groups=new Map();for(const s of g.samples){const key=s.mode+'\u0000'+s.material;const list=groups.get(key)||[];list.push(s);groups.set(key,list);}for(const samples of groups.values())card.append(advisorChart(samples,g.objective));const table=elem('table',undefined,'advisor-table');table.append(elem('caption','Evidencias de esta meta. El porcentaje describe cada muestra.'));const head=elem('tr');for(const label of ['Fecha','Resultado','Modalidad','Material y observación',''])head.append(elem('th',label));const thead=elem('thead');thead.append(head);table.append(thead);const body=elem('tbody');for(const s of [...g.samples].sort((a,b)=>a.date.localeCompare(b.date))){const row=elem('tr');for(const value of [advisorHumanDate(s.date),s.correct+'/'+s.total+' · '+advisorScore(s)+' %',s.mode,[s.material,s.note].filter(Boolean).join(' · ')])row.append(elem('td',value));const control=elem('td');control.append(advisorButton('Corregir',()=>editAdvisorSample(g.id,s.id)));row.append(control);body.append(row);}table.append(body);const wrap=elem('div',undefined,'tablewrap');wrap.append(table);card.append(wrap);}else card.append(elem('p','Todavía no hay muestras registradas para esta meta.','advisor-empty'));
 const sample=elem('details');sample.append(elem('summary','Registrar una evidencia'));const form=elem('form');const base='advisor-sample-'+g.id;form.id=base+'-form';advisorField(form,base+'-date','Fecha',advisorDateToday(),{type:'date',required:true});const row=elem('div',undefined,'advisor-form-row');for(const [key,label,min] of [['correct','Aciertos',0],['total','Total de intentos',1]]){const col=elem('div');advisorField(col,base+'-'+key,label,'',{type:'number',min,maxNumber:1000,required:true});row.append(col);}form.append(row);advisorField(form,base+'-mode','Modalidad','Sin ayuda',{choices:['Sin ayuda','Con apoyo','Al escuchar','Al leer']});advisorField(form,base+'-material','Material o patrón',g.material,{max:500,required:true});advisorField(form,base+'-note','Qué observaste y qué apoyo ofreciste','',{multiline:true,max:1500});const submit=elem('button','Guardar evidencia','advisor-primary');submit.type='submit';form.append(submit);form.addEventListener('submit',async e=>{e.preventDefault();if(submit.disabled)return;submit.disabled=true;try{const s={id:form.dataset.editId||crypto.randomUUID(),date:$(base+'-date').value,correct:Number($(base+'-correct').value),total:Number($(base+'-total').value),mode:$(base+'-mode').value,material:$(base+'-material').value,note:$(base+'-note').value};advisor=checkAdvisor({...advisor,goals:advisor.goals.map(old=>old.id===g.id?{...old,samples:form.dataset.editId?old.samples.map(sample=>sample.id===s.id?s:sample):[...old.samples,s]}:old)});scheduleTeacherSave();await flushTeacherSave();renderAdvisorProgress();renderAdvisorHome();notify('Evidencia guardada. Compara el material y la ayuda antes de interpretar el cambio.');}catch(error){notify(error.message);}finally{submit.disabled=false;}});sample.append(form);card.append(sample,advisorButton('Editar meta',()=>editAdvisorGoal(g.id)));root.append(card);
 }

}
function renderAdvisorComparison(){const root=$('advisor-comparison');if(!root)return;root.replaceChildren();const index=$('advisor-comparison-session')?.value;const session=index!==''?state.sessions[Number(index)]:null;for(const [label,value] of [['Al escuchar',session?.oral||'Por observar'],['Al leer',session?.reading||'Por observar']]){const c=elem('div');c.append(elem('strong',label),elem('p',value));root.append(c);}}
function advisorChart(samples,title){
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 600 180');svg.setAttribute('class','advisor-chart');svg.setAttribute('role','img');svg.setAttribute('aria-label','Precisión de muestras: '+title+' · '+samples[0].mode+' · '+samples[0].material);
 const add=(tag,attrs,text)=>{const n=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;svg.append(n);return n;};const sorted=[...samples].sort((a,b)=>a.date.localeCompare(b.date)).slice(-12);add('text',{x:46,y:22},samples[0].mode+' · '+samples[0].material.slice(0,72));for(const v of [0,50,100]){const y=142-v;add('line',{x1:46,x2:575,y1:y,y2:y,stroke:'#0b1f3a14'});add('text',{x:8,y:y+4},v+'%');}const points=sorted.map((s,i)=>[sorted.length===1?310:46+i*529/(sorted.length-1),142-advisorScore(s)]);if(points.length>1)add('polyline',{points:points.map(p=>p.join(',')).join(' '),fill:'none',stroke:'#238d85','stroke-width':2.5});points.forEach(([x,y],i)=>{const circle=add('circle',{cx:x,cy:y,r:5,fill:'#238d85'});const tip=document.createElementNS(ns,'title');tip.textContent=advisorHumanDate(sorted[i].date)+' · '+sorted[i].correct+'/'+sorted[i].total;circle.append(tip);if(i===0||i===points.length-1)add('text',{x:Math.min(x,527),y:165},sorted[i].date.slice(5));});return svg;
}
function editAdvisorSample(goalId,sampleId){const goal=advisor.goals.find(g=>g.id===goalId);const sample=goal?.samples.find(s=>s.id===sampleId);if(!sample)return;const base='advisor-sample-'+goalId,form=$(base+'-form');form.dataset.editId=sampleId;form.parentElement.open=true;for(const key of ['date','correct','total','mode','material','note'])$(base+'-'+key).value=sample[key];$(base+'-correct').focus();}
function clearAdvisorWorkspace(){for(const id of ['asesor','perfil-asesor','plan-asesor','metas-asesor'])$(id)?.replaceChildren();$('advisor-session-details')?.remove();}
function editAdvisorGoal(id){const g=advisor.goals.find(g=>g.id===id);if(!g)return;const f=$('advisor-goal-form');f.dataset.editId=id;for(const key of ['area','objective','baseline','criterion','support','material','reviewDate'])$('advisor-goal-'+key).value=g[key];f.scrollIntoView({behavior:'smooth'});$('advisor-goal-objective').focus();}
function prepareAdvisorReview(){
 if((assessment.nextGoals||assessment.familySummary)&&!confirm('¿Usar las metas y este balance para actualizar el borrador familiar? Podrás revisarlo antes de publicarlo.'))return;
 assessment.nextGoals=advisor.goals.filter(g=>g.status!=='Consolidada').map(g=>g.objective+'\nCriterio: '+g.criterion+'\nApoyo: '+(g.support||'Por precisar')).join('\n\n').slice(0,5000);
 if(advisor.review.achievements)assessment.familySummary=advisor.review.achievements;if(advisor.review.pending)assessment.needs=advisor.review.pending;
 const current=advisor.goals.find(g=>g.status==='En trabajo');if(current)familyDraft.currentGoal=current.objective;
 if(advisor.review.adjustments)assessment.recommendations=advisor.review.adjustments;assessment.reviewDate=advisorHumanDate(advisor.reviewDate);
 persistAssessment();buildFamilyEditor();advisorGo('publicar');notify('Borrador preparado. Revísalo y publica cuando esté listo para la familia.');
}
function prepareAdvisorSessionReport(){
 const s=state.sessions.at(-1);if(!s){notify('Registra primero un encuentro.');return;}const d=cleanSessionDetail(s.detail||{});if((familyDraft.recentAchievement||familyDraft.moodSummary||familyDraft.homeRecommendation)&&!confirm('¿Actualizar el borrador familiar con el último encuentro?'))return;
 familyDraft.recentAchievement=d.achievement;familyDraft.moodSummary=['Confianza: '+d.confidence,'Participación: '+d.participation,'Cansancio: '+d.fatigue].join('. ')+'.';familyDraft.helpfulSupports=d.support;familyDraft.homeRecommendation=d.home||s.next;const p=advisor.plans.filter(p=>p.status==='Programada'&&p.date.slice(0,10)>=s.date).sort((a,b)=>a.date.localeCompare(b.date))[0];if(p){familyDraft.nextDate=p.date;familyDraft.nextPurpose=p.objective;familyDraft.nextMaterials=p.materials;}
 advisorSave();buildFamilyEditor();advisorGo('publicar');notify('Datos del encuentro llevados al borrador. Revisa la redacción antes de publicarlo.');
}
function buildAssessment(){buildAssessmentCore();const root=$('diagnostico');const summary=$('assessment-counts')?.parentElement;if(!summary)return;const actions=summary.querySelector('.actions');if(actions){actions.replaceChildren(advisorButton('Pasar balance a objetivos',()=>{state.baseline=[assessment.strengths,assessment.needs].filter(Boolean).join('\n').slice(0,1500);state.goals=assessment.nextGoals.slice(0,2000);save();render();advisorGo('metas-asesor');}),advisorButton('Descargar valoración en PDF',downloadAdvisorAssessment));}const note=summary.querySelector('p.muted');if(note)note.textContent='Las observaciones se guardan automáticamente en tu perfil. El reporte familiar se revisa y publica por separado.';}
function render(){renderBase();if(activeRole==='israel'){decorateAdvisorRecords();renderAdvisorHome();}}
function decorateAdvisorRecords(){
 const cards=$('records').children;state.sessions.forEach((s,i)=>{const c=cards[i];if(!c||!s.detail)return;const d=cleanSessionDetail(s.detail);const extra=elem('div',undefined,'advisor-detail');extra.append(elem('p','Confianza: '+d.confidence+' · Participación: '+d.participation+' · Cansancio: '+d.fatigue));for(const [label,value] of [['Apoyos',d.support],['Errores y autocorrecciones',d.errors],['Logro',d.achievement],['En casa',d.home]])if(value)extra.append(elem('p',label+': '+value));c.append(extra);});
}
function advisorSummaryBlocks(){
 const blocks=[['Programa','Segundo de primaria · Tres encuentros por semana · 45 minutos flexibles.'],['Inicio y revisión',advisorHumanDate(advisor.startDate)+' · Revisión: '+advisorHumanDate(advisor.reviewDate)]];
 for(const [key,label] of Object.entries(advisorLabels))if(advisor.context[key])blocks.push([label,advisor.context[key]]);
 if(assessment.strengths)blocks.push(['Fortalezas',assessment.strengths]);if(assessment.needs)blocks.push(['Prioridades',assessment.needs]);
 for(const g of advisor.goals){blocks.push([g.area+' · '+g.status,[g.objective,'Punto de partida: '+g.baseline,'Criterio: '+g.criterion,'Apoyo: '+g.support,'Material: '+g.material,'Revisión: '+advisorHumanDate(g.reviewDate)].join('\n')]);for(const s of g.samples)blocks.push(['Evidencia · '+advisorHumanDate(s.date),s.correct+'/'+s.total+' · '+advisorScore(s)+' % · '+s.mode+'\n'+s.material+'\n'+s.note]);}
 for(const s of state.sessions){const d=cleanSessionDetail(s.detail||{});blocks.push(['Encuentro · '+advisorHumanDate(s.date),[s.objective,s.material,s.total!==null?'Lectura: '+s.correct+'/'+s.total:'','Al escuchar: '+s.oral,'Al leer: '+s.reading,s.evidence,'Apoyos: '+d.support,'Errores y autocorrecciones: '+d.errors,'Confianza: '+d.confidence+' · Participación: '+d.participation+' · Cansancio: '+d.fatigue,'Logro: '+d.achievement,'En casa: '+(d.home||s.next)].filter(Boolean).join('\n')]);}
 for(const [key,label] of [['achievements','Avances'],['pending','Necesidades pendientes'],['adjustments','Ajustes'],['school','Coordinación escolar'],['decision','Decisión de continuidad']])if(advisor.review[key])blocks.push([label,advisor.review[key]]);return blocks;
}
function downloadAdvisorSummary(){downloadAdvisorPDF('Seguimiento pedagógico',advisorSummaryBlocks(),'seguimiento-asesor');}
function downloadAdvisorPlan(p){downloadAdvisorPDF('Ficha del encuentro',[[advisorHumanDate(p.date)+' · Semana '+p.week,p.kind+'\n'+p.objective],['Patrones y materiales',[p.patterns,p.materials].filter(Boolean).join('\n')],...p.blocks.map(b=>[b.title+' · '+b.minutes+' min',b.description]),['Práctica para casa',p.home]],'plan-encuentro');}
function downloadAdvisorAssessment(){const blocks=[['Contexto',assessment.context],['Fortalezas',assessment.strengths],['Prioridades',assessment.needs],['Metas propuestas',assessment.nextGoals]];sessionsPlan.forEach((p,i)=>{blocks.push(['Sesión '+(i+1)+' · '+p.title,assessment.notes[i]||'Sin nota de cierre.']);for(const t of p.tasks){const lines=t.items.map((item,n)=>{const o=assessment.observations[taskKey(t,n)];return item+' · '+(o?rubric[o.level]:'Sin aplicar')+(o?.response?'\n'+o.response:'');});blocks.push([t.area+' · '+t.title,lines.join('\n\n')]);}});downloadAdvisorPDF('Valoración pedagógica inicial',blocks,'valoracion-inicial');}
function downloadAdvisorPDF(title,blocks,name){
 const pages=[],objects=['','', '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'];let page,y;const encode=childPDFText;
 const write=(text,size=11,bold=false,color='0.043 0.122 0.227')=>{page.push('BT /'+(bold?'F2':'F1')+' '+size+' Tf '+color+' rg 1 0 0 1 42 '+(841.89-y).toFixed(2)+' Tm ('+encode(text)+') Tj ET');};
 const newPage=()=>{page=[];pages.push(page);page.push('0.043 0.122 0.227 rg 0 756.89 595.28 85 re f','0.137 0.553 0.522 rg 0 749.89 595.28 7 re f');y=28;write('LEARNING & DEVELOPMENT STUDIO',11,true,'1 1 1');y=60;write(title,20,true,'1 1 1');y=112;};newPage();write('Israel Ventura · '+advisorHumanDate(advisorDateToday()));y+=30;
 const wrap=text=>{const result=[];for(const paragraph of String(text).split('\n')){let line='';for(const word of paragraph.split(/\s+/)){for(const part of word.match(/.{1,70}/g)||['']){if((line+' '+part).length>78&&line){result.push(line);line='';}line+=(line?' ':'')+part;}}result.push(line);}return result;};
 for(const [heading,content] of blocks){if(!content)continue;const headings=wrap(heading);if(y+headings.length*19+38>780)newPage();for(const line of headings){write(line,12,true,'0.137 0.553 0.522');y+=19;}y+=7;for(const line of wrap(content)){if(y+17>780)newPage();write(line);y+=17;}y+=17;}
 const kids=[];pages.forEach((lines,i)=>{lines.push('BT /F1 9 Tf 0.34 0.42 0.49 rg 1 0 0 1 42 28 Tm ('+encode('Uso del asesor · '+(i+1)+' / '+pages.length)+') Tj ET');const stream=lines.join('\n')+'\n';const content=objects.length+1;objects.push('<< /Length '+stream.length+' >>\nstream\n'+stream+'endstream');const id=objects.length+1;objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents '+content+' 0 R >>');kids.push(id+' 0 R');});objects[0]='<< /Type /Catalog /Pages 2 0 R >>';objects[1]='<< /Type /Pages /Kids ['+kids.join(' ')+'] /Count '+pages.length+' >>';let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=pdf.length;pdf+='xref\n0 '+(objects.length+1)+'\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size '+(objects.length+1)+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF\n';const blob=new Blob([Uint8Array.from(pdf,c=>c.charCodeAt(0))],{type:'application/pdf'});const url=URL.createObjectURL(blob),a=elem('a');a.href=url;a.download=name+'-'+advisorDateToday()+'.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
