function familyDate(value){if(!value)return 'Por acordar';const date=new Date(value);return Number.isNaN(date.valueOf())?value:date.toLocaleString('es-MX',{timeZone:'America/Mexico_City',dateStyle:'medium',timeStyle:'short'});}
function familyPanel(id,title){const section=elem('section',undefined,'family-pane');section.id='family-pane-'+id;section.hidden=id!=='summary';section.append(elem('h3',title));return section;}
function familyText(id,fallback){const p=elem('p',fallback,'preserve-lines');p.id=id;return p;}
function familyTab(id){document.querySelectorAll('.family-pane').forEach(p=>p.hidden=p.id!=='family-pane-'+id);document.querySelectorAll('[data-family-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.familyTab===id)));}
function buildFamily(){
 const root=$('reportes');root.replaceChildren();
 const hero=elem('div',undefined,'family-hero');hero.append(elem('span','ESPACIO DE LA FAMILIA','discover-eyebrow'),elem('h2','Acompañamos sus descubrimientos.'),elem('p','Un paso a la vez, con calma y en equipo.','family-lead'));
 const connection=elem('p','Consultando el seguimiento…','family-updated');connection.id='family-updated';hero.append(connection);root.append(hero);
 const highlights=elem('div',undefined,'family-highlights');
 [['achievement','Un logro reciente','Primero conoceremos sus fortalezas.'],['goal','Nuestro objetivo','Conocer su punto de partida.'],['home','Para casa','La primera recomendación llegará después del encuentro.']].forEach(([id,title,fallback])=>{const card=elem('article',undefined,'family-highlight');card.append(elem('span',title,'family-kicker'),familyText('family-highlight-'+id,fallback));highlights.append(card);});root.append(highlights);
 const tabs=elem('div',undefined,'family-tabs');tabs.setAttribute('role','navigation');tabs.setAttribute('aria-label','Seguimiento familiar');
 [['summary','Resumen de Israel'],['discoveries','Sus descubrimientos'],['mood','Cómo se sintió'],['home','En casa'],['next','Próximo encuentro'],['reports','Reportes y dudas']].forEach(([id,title])=>{const b=action(title,()=>familyTab(id));b.dataset.familyTab=id;b.setAttribute('aria-pressed',String(id==='summary'));tabs.append(b);});root.append(tabs);
 const summary=familyPanel('summary','La mirada de Israel');summary.append(familyText('family-summary','El resumen se publicará después de los primeros encuentros.'),elem('h4','Sus fortalezas'),familyText('family-strengths','Por conocer durante la valoración.'),elem('h4','Lo que estamos trabajando'),familyText('family-needs','Las prioridades se definirán a partir de lo que observemos.'),elem('h4','El siguiente paso'),familyText('family-goals','Primero conoceremos qué apoyos le ayudan a aprender.'));root.append(summary);
 const discoveries=familyPanel('discoveries','Sus descubrimientos');discoveries.append(elem('p','Aquí aparecen las actividades terminadas. Israel compartirá lo que muestran sobre su aprendizaje.'),elem('div',undefined,'family-discoveries'));discoveries.lastElementChild.id='family-discoveries';root.append(discoveries);
 const mood=familyPanel('mood','Cómo vivió los encuentros');mood.append(familyText('family-mood','Después del encuentro, Israel compartirá lo que observó sobre su confianza, participación y cansancio.'),elem('h4','Los apoyos que le ayudaron'),familyText('family-supports','Por observar.'),elem('h4','¿Qué observaron en casa?'));const notes=familyMessageForm('observacion','family-observation','Compartan algo que notaron en su ánimo, disposición o cansancio.');mood.append(notes);root.append(mood);
 const home=familyPanel('home','Un momento para acompañarlo');home.append(elem('span','5–10 minutos · A su ritmo','family-home-pill'),familyText('family-home-activity','La actividad para casa aparecerá después de que Israel la prepare.'),action('🔊 Escuchar la recomendación',()=>{if(familyReport)childSpeak(familyReport.homeRecommendation||familyReport.recommendations||'La recomendación está pendiente.');}),elem('p','Elijan un momento tranquilo. Celebren el intento y hagan una pausa si se cansa.','family-kind-note'));root.append(home);
 const next=familyPanel('next','Nuestro próximo encuentro');next.append(elem('h4','Fecha y hora'),familyText('family-next-date','Por acordar con Israel.'),elem('h4','Qué vamos a trabajar'),familyText('family-next-purpose','Se definirá después de la valoración inicial.'),elem('h4','Qué necesitan traer'),familyText('family-next-materials','Israel les avisará si hace falta algún material.'));root.append(next);
 const reports=familyPanel('reports','Reportes y dudas');const history=elem('div');history.id='family-report-history';reports.append(history,elem('h4','Un espacio para preguntar'),familyMessageForm('pregunta','family-question','Escriban una duda o algo que quieran conversar con Israel.'));const messages=elem('div');messages.id='family-messages';reports.append(messages);root.append(reports);renderFamilyReport();
}
function familyMessageForm(kind,id,label){
 const form=elem('form',undefined,'family-message-form');const l=elem('label',label);const input=elem('textarea');input.id=id;input.maxLength=2000;input.rows=3;input.required=true;l.htmlFor=id;const status=elem('p','', 'muted');status.setAttribute('role','status');const submit=elem('button',kind==='observacion'?'Compartir observación':'Enviar a Israel');submit.type='submit';
 form.append(l,input,submit,status);form.addEventListener('submit',async e=>{e.preventDefault();if(activeRole!=='padres'){status.textContent='Los papás pueden enviar mensajes desde su perfil.';return;}submit.disabled=true;try{await cloudRequest('/api/questions',{method:'POST',body:{kind,message:input.value}});input.value='';status.textContent='Mensaje guardado. Israel podrá leerlo en su perfil.';await refreshFamily();}catch(error){status.textContent=error.message;}finally{submit.disabled=false;}});return form;
}
function renderFamilyReport(){
 if(!$('family-summary'))return;const report=familyReport||{};const completed=familySnapshot.discoveries||[];
 const update=(id,value,fallback)=>{if($(id))$(id).textContent=value||fallback;};
 update('family-highlight-achievement',report.recentAchievement|| (completed[0]?'Terminó «'+completed[0].name+'».':''),'Primero conoceremos sus fortalezas.');
 update('family-highlight-goal',report.currentGoal||report.goals,'Conocer su punto de partida.');
 update('family-highlight-home',report.homeRecommendation||report.recommendations,'La primera recomendación llegará después del encuentro.');
 update('family-summary',report.summary,'El resumen se publicará después de los primeros encuentros.');update('family-strengths',report.strengths,'Por conocer durante la valoración.');update('family-needs',report.needs,'Las prioridades se definirán a partir de lo que observemos.');update('family-goals',report.goals||report.currentGoal,'Primero conoceremos qué apoyos le ayudan a aprender.');
 update('family-mood',report.moodSummary,'Después del encuentro, Israel compartirá lo que observó sobre su confianza, participación y cansancio.');update('family-supports',report.helpfulSupports,'Por observar.');update('family-home-activity',report.homeRecommendation||report.recommendations,'La actividad para casa aparecerá después de que Israel la prepare.');
 update('family-next-date',report.nextDate?familyDate(report.nextDate):report.review,'Por acordar con Israel.');update('family-next-purpose',report.nextPurpose,'Se definirá después de la valoración inicial.');update('family-next-materials',report.nextMaterials,'Israel les avisará si hace falta algún material.');
 update('family-updated',cloudConnected?'Seguimiento actualizado · '+new Date().toLocaleTimeString('es-MX',{timeZone:'America/Mexico_City',hour:'2-digit',minute:'2-digit'}):'El seguimiento aparecerá cuando inicien los encuentros.','');
 const discoveries=$('family-discoveries');discoveries.replaceChildren();if(!completed.length)discoveries.append(elem('p','Todavía no hay actividades terminadas. Sus descubrimientos aparecerán aquí al completarlas.','family-empty'));
 completed.forEach(activity=>{const item=elem('article',undefined,'family-discovery');const badge=elem('span','✓','family-discovery-check');badge.setAttribute('aria-hidden','true');const copy=elem('div');copy.append(elem('h4',activity.name),elem('p','Encuentro '+activity.session+' · '+activity.count+' ejercicios realizados'),elem('small',familyDate(activity.completedAt)));item.append(badge,copy);discoveries.append(item);});
 const history=$('family-report-history');history.replaceChildren();const reports=familySnapshot.reports?.length?familySnapshot.reports:(familyReport?[familyReport]:[]);if(!reports.length)history.append(elem('p','El primer reporte estará disponible después de que Israel lo revise y publique.','family-empty'));
 reports.forEach(report=>{const item=elem('article',undefined,'family-report-card');item.append(elem('span','Reporte de Israel · '+(report.issued||familyDate(report.publishedAt)),'family-kicker'),elem('p',report.summary),action('Descargar PDF',()=>downloadFamilyPDF(report)));history.append(item);});
 const messages=$('family-messages');messages.replaceChildren();for(const m of familySnapshot.questions||[]){const item=elem('article',undefined,'family-message');item.append(elem('small',(m.kind==='observacion'?'Observación de la familia':'Pregunta de la familia')+' · '+familyDate(m.created_at)),elem('p',m.message));if(m.answer)item.append(elem('strong','Israel respondió'),elem('p',m.answer));else item.append(elem('small','Pendiente de respuesta.'));messages.append(item);}
}
function makeFamilyReport(){
 return {type:'lds-family-report',version:2,issued:new Date().toLocaleDateString('es-MX',{timeZone:'America/Mexico_City'}),summary:assessment.familySummary,strengths:assessment.strengths,needs:assessment.needs,goals:assessment.nextGoals,recommendations:assessment.recommendations,review:assessment.reviewDate,...familyDraft,activities:sessionsPlan.map((p,i)=>({title:'Sesión '+(i+1)+' · '+p.title,status:p.tasks.some(t=>t.items.some((_,n)=>{const o=assessment.observations[taskKey(t,n)];return o&&!['pendiente','no_aplicado'].includes(o.level);}))?'Con observaciones registradas':'Pendiente de aplicar'}))};
}
function buildFamilyEditor(){
 const root=$('publicar');root.replaceChildren();const card=elem('div',undefined,'card family-editor');card.append(elem('span','SEGUIMIENTO FAMILIAR','discover-eyebrow'),elem('h2','Preparar el próximo reporte'),elem('p','Tu borrador se guarda automáticamente. Los papás verán el reporte cuando lo publiques.'));
 [['familySummary','Resumen para la familia'],['recommendations','Recomendaciones generales para casa'],['reviewDate','Próxima revisión del acompañamiento']].forEach(([key,label])=>makeArea(card,key,label,assessment[key],value=>assessment[key]=value));
 card.append(elem('p','Las fortalezas, prioridades y objetivos se editan en Valoración inicial.','muted'));
 [['recentAchievement','Un logro reciente'],['currentGoal','El objetivo actual, en una frase'],['homeRecommendation','Actividad concreta para casa: qué hacer y cómo acompañarlo'],['moodSummary','Confianza, participación y cansancio observados'],['helpfulSupports','Los apoyos que le ayudaron'],['nextPurpose','Propósito del próximo encuentro'],['nextMaterials','Materiales para el próximo encuentro']].forEach(([key,label])=>makeArea(card,'family-'+key,label,familyDraft[key]||'',value=>{familyDraft[key]=value;scheduleTeacherSave();}));
 const l=elem('label','Fecha y hora del próximo encuentro'),date=elem('input');date.type='datetime-local';date.value=familyDraft.nextDate||'';date.addEventListener('input',()=>{familyDraft.nextDate=date.value;scheduleTeacherSave();});card.append(l,date);
 const actions=elem('div',undefined,'actions');actions.append(action('Vista previa familiar',()=>{familyReport=makeFamilyReport();buildFamily();show('reportes');}),action('Publicar reporte para los papás',async()=>{if(!assessment.familySummary.trim()){notify('Escribe y revisa el resumen antes de publicarlo.');return;}try{await flushTeacherSave();const result=await cloudRequest('/api/reports',{method:'POST',body:makeFamilyReport()});familyReport=result.report;await refreshFamily();notify('Reporte publicado. Los papás lo verán al entrar a su perfil.');}catch(error){notify(error.message);}}));card.append(actions);root.append(card);
 const evidence=elem('div',undefined,'card');evidence.append(elem('h3','Descubrimientos guardados del alumno'));const list=elem('div');list.id='teacher-cloud-runs';evidence.append(list,action('Actualizar descubrimientos y mensajes',()=>refreshFamily().catch(error=>notify(error.message))));root.append(evidence);
 const questions=elem('div',undefined,'card');questions.append(elem('h3','Mensajes de la familia'));const q=elem('div');q.id='teacher-family-questions';questions.append(q);root.append(questions);renderTeacherCloud();
}
function renderTeacherCloud(){
 const root=$('teacher-cloud-runs');if(!root)return;root.replaceChildren();if(!teacherRuns.length)root.append(elem('p','Todavía no hay respuestas guardadas. Aparecerán aquí cuando el alumno realice las actividades.','muted'));
 teacherRuns.forEach(run=>{const task=visualTasks.find(t=>t.id===run.task_id);const details=elem('details');details.append(elem('summary',(task?.name||'Actividad')+' · '+(run.completed_at?'Terminada':'En proceso')+' · '+familyDate(run.updated_at)));(run.trials||[]).forEach(t=>details.append(elem('p','Ejercicio '+t.item+' · Respuesta: '+t.response+' · Referencia: '+t.expected+' · Audio de apoyo: '+(t.audioHelp?'sí':'no'))));root.append(details);});
 const questions=$('teacher-family-questions');if(!questions)return;if(questions.contains(document.activeElement))return;questions.replaceChildren();if(!familySnapshot.questions?.length)questions.append(elem('p','Todavía no hay mensajes de la familia.','muted'));
 for(const q of familySnapshot.questions||[]){const article=elem('article',undefined,'family-message');article.append(elem('small',(q.kind==='observacion'?'Observación':'Pregunta')+' · '+familyDate(q.created_at)),elem('p',q.message));const input=elem('textarea');input.value=q.answer||'';input.maxLength=5000;input.setAttribute('aria-label','Respuesta de Israel');article.append(input,action(q.answer?'Actualizar respuesta':'Responder a la familia',async()=>{try{await cloudRequest('/api/questions/'+q.id,{method:'PUT',body:{answer:input.value}});await refreshFamily();renderTeacherCloud();notify('Respuesta guardada y disponible para la familia.');}catch(error){notify(error.message);}}));questions.append(article);}
}
async function cloudRequest(path,options={}){
 if(!LDS_CLOUD||!cloudCode)throw Error('Abre la plataforma de Sites e ingresa tu código para guardar el seguimiento.');
 const response=await fetch(path,{method:options.method||'GET',headers:{'x-lds-role':activeRole||cloudRole,'x-lds-code':cloudCode,...(options.body?{'content-type':'application/json'}:{})},body:options.body?JSON.stringify(options.body):undefined,cache:'no-store'});
 const value=await response.json();if(!response.ok)throw Error(value.error||'No se pudo guardar. Vuelve a intentar.');return value;
}
async function connectCloudRole(role,code){cloudRole=role;cloudCode=code;try{await cloudRequest('/api/session');cloudConnected=true;}catch(error){cloudCode='';cloudRole=null;cloudConnected=false;throw error;}}
async function loadCloudDashboard(){
 if(!cloudConnected)return;
 if(activeRole==='israel'){
  const value=await cloudRequest('/api/teacher');const docs=value.documents||{};
  if(docs.state)state=validate(docs.state);if(docs.assessment)assessment=checkAssessment(docs.assessment);if(docs.familyDraft)familyDraft={...docs.familyDraft};
  teacherRuns=value.runs||[];familySnapshot=value;familyReport=value.reports?.[0]||null;render();buildAssessment();buildFamilyEditor();buildFamily();storageMessage();
 }else if(activeRole==='padres'){await refreshFamily();}
 clearInterval(cloudPoll);if(['padres','israel'].includes(activeRole))cloudPoll=setInterval(()=>{if(document.visibilityState==='visible')refreshFamily().catch(()=>{if($('family-updated'))$('family-updated').textContent='No se pudo actualizar. Conservamos el último seguimiento disponible.';});},20000);
}
async function refreshFamily(){if(!cloudConnected||!['padres','israel'].includes(activeRole))return;const value=await cloudRequest(activeRole==='israel'?'/api/teacher':'/api/family');familySnapshot=value;familyReport=value.reports?.[0]||null;if(activeRole==='israel'){teacherRuns=value.runs||[];renderTeacherCloud();}renderFamilyReport();}
function scheduleTeacherSave(){if(!cloudConnected||activeRole!=='israel')return;clearTimeout(teacherSaveTimer);teacherSaveTimer=setTimeout(()=>flushTeacherSave().catch(error=>notify(error.message)),500);}
async function flushTeacherSave(){clearTimeout(teacherSaveTimer);teacherSaveTimer=null;if(!cloudConnected||activeRole!=='israel')return;syncGoals();const payload=JSON.parse(JSON.stringify({state,assessment,familyDraft}));teacherSaveChain=teacherSaveChain.catch(()=>{}).then(()=>cloudRequest('/api/teacher',{method:'PUT',body:payload}));await teacherSaveChain;storageMessage();}
function beginCloudRun(){cloudRunId=crypto.randomUUID();cloudRunRevision=0;}
function saveCloudRun(complete=false){
 if(!cloudConnected||!['alumno','israel'].includes(activeRole)||!childCurrent)return;
 const run={id:cloudRunId,task:childCurrent.id,revision:++cloudRunRevision,trials:childTrials.slice(childRunStart).map(t=>({...t})),complete};if(!run.trials.length)return;
 cloudPendingRuns.set(run.id,run);flushCloudRuns();
}
async function flushCloudRuns(){
 if(cloudFlushing||!cloudConnected)return;cloudFlushing=true;
 try{for(const [id,payload] of cloudPendingRuns){await cloudRequest('/api/runs',{method:'POST',body:payload});if(cloudPendingRuns.get(id)?.revision===payload.revision)cloudPendingRuns.delete(id);}if($('child-save-status'))$('child-save-status').textContent=cloudPendingRuns.size?'Guardando tus descubrimientos…':'Tus descubrimientos están guardados.';}
 catch(error){if($('child-save-status'))$('child-save-status').textContent='No se pudo guardar todavía. Revisa tu conexión y vuelve a intentar.';notify(error.message);}
 finally{cloudFlushing=false;if(cloudPendingRuns.size&&navigator.onLine){clearTimeout(cloudRetry);cloudRetry=setTimeout(flushCloudRuns,4000);}}
}
async function closeCloud(){if(cloudConnected&&activeRole==='israel')await flushTeacherSave();await flushCloudRuns();if(cloudPendingRuns.size)throw Error('Hay descubrimientos pendientes de guardar. Revisa tu conexión antes de cerrar.');clearInterval(cloudPoll);clearTimeout(cloudRetry);clearTimeout(teacherSaveTimer);cloudConnected=false;cloudCode='';cloudRole=null;}
function downloadFamilyPDF(report){
 const blocks=[['Resumen de Israel',report.summary],['Un logro reciente',report.recentAchievement],['Fortalezas',report.strengths],['Objetivo actual',report.currentGoal||report.goals],['Prioridades',report.needs],['Cómo se sintió',report.moodSummary],['Apoyos que le ayudaron',report.helpfulSupports],['Para acompañarlo en casa',report.homeRecommendation||report.recommendations],['Próximo encuentro',[(report.nextDate?familyDate(report.nextDate):report.review),report.nextPurpose,report.nextMaterials].filter(Boolean).join('\n')]].filter(([,value])=>value);
 const pages=[];let lines=[],y=112;const width=595.28,height=841.89,margin=42;const encode=childPDFText;
 const write=(text,top,size=11,bold=false,color='0.043 0.122 0.227')=>lines.push('BT /'+(bold?'F2':'F1')+' '+size+' Tf '+color+' rg 1 0 0 1 '+margin+' '+(height-top).toFixed(2)+' Tm ('+encode(text)+') Tj ET');
 const newPage=()=>{lines=[];pages.push(lines);lines.push('0.043 0.122 0.227 rg 0 756.89 595.28 85 re f','0.137 0.553 0.522 rg 0 749.89 595.28 7 re f');write('LEARNING & DEVELOPMENT STUDIO',28,11,true,'1 1 1');write('Seguimiento familiar',60,22,true,'1 1 1');y=112;};newPage();write('Israel Ventura · '+(report.issued||familyDate(report.publishedAt)),y,11);y+=34;
 for(const [label,value] of blocks){if(y+70>height-60)newPage();write(label,y,13,true,'0.137 0.553 0.522');y+=24;for(const paragraph of value.split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if((line+' '+word).length>82&&line){if(y+17>height-60)newPage();write(line,y);y+=17;line='';}line+=(line?' ':'')+word;}if(y+17>height-60)newPage();write(line,y);y+=17;}y+=17;}
 pages.forEach((page,i)=>page.push('BT /F1 9 Tf 0.34 0.42 0.49 rg 1 0 0 1 42 28 Tm ('+encode('Acompañamiento individual · '+(i+1)+' / '+pages.length)+') Tj ET'));
 const objects=['','', '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'],kids=[];
 pages.forEach(page=>{const stream=page.join('\n')+'\n',content=objects.length+1;objects.push('<< /Length '+stream.length+' >>\nstream\n'+stream+'endstream');const id=objects.length+1;objects.push('<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents '+content+' 0 R >>');kids.push(id+' 0 R');});objects[0]='<< /Type /Catalog /Pages 2 0 R >>';objects[1]='<< /Type /Pages /Kids ['+kids.join(' ')+'] /Count '+pages.length+' >>';
 let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((object,i)=>{offsets.push(pdf.length);pdf+=(i+1)+' 0 obj\n'+object+'\nendobj\n';});const xref=pdf.length;pdf+='xref\n0 '+(objects.length+1)+'\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size '+(objects.length+1)+' /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF\n';const url=URL.createObjectURL(new Blob([Uint8Array.from(pdf,c=>c.charCodeAt(0))],{type:'application/pdf'})),link=elem('a');link.href=url;link.download='seguimiento-familiar-'+(report.publishedAt||new Date().toISOString()).slice(0,10)+'.pdf';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);
}
